FROM mcr.microsoft.com/dotnet/sdk:6.0 AS sdk6

FROM mcr.microsoft.com/dotnet/sdk:10.0.201
COPY --from=sdk6 /usr/share/dotnet/shared/ /usr/share/dotnet/shared/
COPY --from=sdk6 /usr/share/dotnet/sdk/ /usr/share/dotnet/sdk/
COPY --from=sdk6 /usr/share/dotnet/sdk-manifests/ /usr/share/dotnet/sdk-manifests/
COPY --from=sdk6 /usr/share/dotnet/packs/ /usr/share/dotnet/packs/
