FROM mcr.microsoft.com/dotnet/sdk:10.0.201 AS sdk10

FROM mcr.microsoft.com/dotnet/sdk:11.0.100-rc.1
COPY --from=sdk10 /usr/share/dotnet/shared/ /usr/share/dotnet/shared/
COPY --from=sdk10 /usr/share/dotnet/sdk/ /usr/share/dotnet/sdk/
COPY --from=sdk10 /usr/share/dotnet/sdk-manifests/ /usr/share/dotnet/sdk-manifests/
COPY --from=sdk10 /usr/share/dotnet/packs/ /usr/share/dotnet/packs/
