namespace EasyDotnet.Domain.Models.MsBuild.Project;

public sealed record DotnetProjectV1(
    string ProjectName,
    string Language,
    string? OutputPath,
    string? OutputType,
    string? TargetExt,
    string? AssemblyName,
    string? TargetFramework,
    string[]? TargetFrameworks,
    bool IsTestProject,
    bool IsWebProject,
    bool IsWorkerProject,
    string? UserSecretsId,
    bool TestingPlatformDotnetTestSupport,
    string? TargetPath,
    bool GeneratePackageOnBuild,
    bool IsPackable,
    string? LangVersion,
    string? RootNamespace,
    string? PackageId,
    string? NugetVersion,
    string? Version,
    string? PackageOutputPath,
    bool IsMultiTarget,
    bool IsNetFramework,
    bool UseIISExpress,
    string RunCommand,
    string BuildCommand,
    string TestCommand,
    bool IsAspireHost,
    Version? AspireHostingSdkVersion
);