namespace EasyDotnet.MsBuild;

public record DotnetProject
(
    string? OutputPath,
    string? OutputType,
    string? OutDir,
    string? TargetExt,
    string? TargetDir,
    string? TargetName,
    bool IsTestProject,
    bool IsTestingPlatformApplication,
    string? RunSettingsFilePath,
    string? AssemblyName,
    string? TargetFramework,
    string[]? TargetFrameworks,
    string? UserSecretsId,
    bool TestingPlatformDotnetTestSupport,
    string? TargetPath,
    bool GeneratePackageOnBuild,
    bool IsPackable,
    string? PackageId,
    Version? Version,
    string? PackageOutputPath,
    string? TargetFrameworkVersion,
    bool UsingMicrosoftNETSdk,
    bool UsingGodotNETSdk,
    bool UsingMicrosoftNETSdkWorker,
    bool UsingMicrosoftNETSdkWeb,
    bool UsingMicrosoftNETSdkRazor,
    bool UsingMicrosoftNETSdkStaticWebAssets,
    bool UsingMicrosoftNETSdkBlazorWebAssembly,
    bool UseIISExpress,
    string? LangVersion,
    string? RootNamespace,
    string? RunWorkingDirectory,
    bool IsAspireHost,
    Version? AspireHostingSDKVersion,
    bool IsLegacyAspire,
    string? AspireRidToolExecutable,
    string? AspireRidToolRoot,
    string? AspireRidToolDirectory,
    string? DcpDir,
    string? DcpExtensionsDir,
    string? DcpBinDir,
    string? AspireManifestPublishOutputPath,
    string? AspireDashboardPath,
    string? AspireDashboardDir,
    string? AspirePublisher,
    bool SkipAspireWorkloadManifest,
    string? AspireGeneratedClassesVisibility,
    bool EnableDefaultCompileItems,
    bool EnableDefaultContentItems,
    bool EnableDefaultRazorGenerateItems,
    bool EnableDefaultRazorComponentItems,
    bool CopyRazorGenerateFilesToPublishDirectory,
    string? RazorCompileToolset,
    bool IncludeRazorContentInPack,
    string? RazorGenerateOutputFileExtension,
    string[]? RazorUpToDateReloadFileTypes,
    Version? RazorLangVersion,
    bool AddRazorSupportForMvc,
    string? RazorDefaultConfiguration,
    bool EnableDefaultItems,
    bool EnableDefaultEmbeddedResourceItems,
    bool EnableDefaultNoneItems,
    bool IsPublishable,
    bool IsNETCoreOrNETStandard,
    string? PublishDir,
    string? PublishDirName,
    string? AppDesignerFolder,
    bool Optimize,
    string? DebugType,
    string? RestoreProjectStyle,
    bool TreatWarningsAsErrors,
    string? MSBuildToolsPath,
    string? NetCoreTargetingPackRoot,
    string? NetCoreRoot,
    string? DOTNET_HOST_PATH,
    string? NETCoreAppMaximumVersion,
    string? BundledNETCoreAppTargetFrameworkVersion,
    string? BundledNETCoreAppPackageVersion,
    string? DefaultLanguageSourceExtension,
    string[]? NoWarn,
    string? VisualStudioVersion,
    string? MaxSupportedLangVersion,
    string? TargetFrameworkIdentifier,
    string? MSBuildProjectName,
    string? ProjectDir,
    string? ProjectName,
    string? MSBuildProjectFullPath,
    string? MicrosoftNETBuildTasksDirectoryRoot,
    string? MicrosoftNETBuildTasksDirectory,
    string? MicrosoftNETBuildTasksAssembly,
    string? MicrosoftNETBuildTasksTFM,
    bool HasRuntimeOutput,
    string? RoslynTargetsPath,
    string? RoslynTasksAssembly,
    string[]? DefaultImplicitPackages,
    string? MSBuildProjectFile,
    string? ProjectPath,
    string? Language,
    string? BundledNETStandardTargetFrameworkVersion,
    string? BundledNETStandardPackageVersion,
    string? BundledNETCorePlatformsPackageVersion,
    string? BundledRuntimeIdentifierGraphFile,
    string? NETCoreSdkVersion,
    string? SdkAnalysisLevel,
    string? NETCoreSdkRuntimeIdentifier,
    string? NETCoreSdkPortableRuntimeIdentifier,
    bool NETCoreSdkIsPreview,
    bool TargetsNet9,
    bool TargetsNet8,
    bool TargetsNet7,
    bool TargetsNet6,
    bool TargetsCurrent,
    bool IsNetCoreAppTargetingLatestTFM,
    string? RestoreTool,
    bool RestoreSuccess,
    string? ProjectAssetsFile,
    string? NuGetPackageRoot,
    string[]? NuGetPackageFolders,
    string? NuGetProjectStyle,
    string? NuGetToolVersion,
    string[]? Configurations,
    string? Configuration,
    string[]? Platforms,
    string? Platform,
    bool DebugSymbols,
    bool ImportDirectoryBuildProps,
    bool ImportDirectoryPackagesProps,
    string? MinimumMSBuildVersion,
    string? BundledMSBuildVersion,
    string? MSBuildBinPath,
    string? DefaultAppHostRuntimeIdentifier,
    string? RunCommand,
    string? RunArguments,
    string? ProjectDepsFileName,
    string? ProjectDepsFilePath,
    string? ProjectRuntimeConfigFileName,
    string? ProjectRuntimeConfigFilePath,
    string? ProjectRuntimeConfigDevFilePath,
    bool IncludeMainProjectInDepsFile,
    bool TrimDepsJsonLibrariesWithoutAssets,
    string? GeneratedAssemblyInfoFile,
    bool GenerateAssemblyInfo,
    string? TargetFileName,
    string? IntermediateOutputPath,
    string? BaseIntermediateOutputPath,
    string? MSBuildProjectExtensionsPath,
    bool SelfContained,
    string? UserProfileRuntimeStorePath,
    string? TargetPlatformIdentifier
);

public static class DotnetProjectExtensions
{
  public static bool IsRunnable(this DotnetProject project) => project.OutputType?.Equals("Exe", StringComparison.OrdinalIgnoreCase) == true || project.OutputType?.Equals("WinExe", StringComparison.OrdinalIgnoreCase) == true || project.UseIISExpress;
  public static string? GetLaunchSettingsPath(this DotnetProject project)
  {
    var targetPath = project.MSBuildProjectFullPath;
    if (targetPath is null)
    {
      return null;
    }

    var baseDir = File.Exists(targetPath) ? Path.GetDirectoryName(targetPath)! : targetPath;
    return Path.Combine(baseDir, "Properties", "launchSettings.json");
  }

  //https://github.com/microsoft/testfx/issues/7397
  public static bool IsMTP(this DotnetProject project) => project.IsTestingPlatformApplication;
  public static bool IsVsTest(this DotnetProject project) => !project.IsTestingPlatformApplication && project.IsTestProject;
}