name: 🛠 CI build

on:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'

      - name: Check formatting
        run: dotnet format ./EasyDotnet.sln --verify-no-changes

      - name: Build
        run: dotnet build 

      - name: Generate RPC docs
        run: dotnet run --project ./EasyDotnet.Tool/EasyDotnet.csproj -- --generate-rpc-docs-md > rpcDoc.md

      - name: Check for uncommitted changes (rpcDoc.md)
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"
          git add rpcDoc.md
          git status
          git diff HEAD -- rpcDoc.md || true
          if ! git diff --quiet HEAD -- rpcDoc.md; then
            echo "rpcDoc.md is outdated. Please regenerate and commit changes."
            git --no-pager diff HEAD -- rpcDoc.md
            exit 1
          fi

