name: 🛠 Matrix testing 

on:
  pull_request:

jobs:
  test:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'

      - name: Build
        run: dotnet build

      - name: Test
        run: dotnet test --no-build  ./EasyDotnet.IntegrationTests/EasyDotnet.IntegrationTests.csproj

      - name: BuildServer Smoke Tests
        run: dotnet test --no-build ./EasyDotnet.BuildServer.SmokeTests/EasyDotnet.BuildServer.SmokeTests.csproj

      - name: Test MTP
        run: |
          dotnet run --no-build --project ./EasyDotnet.Debugger.Tests
          dotnet run --no-build --project ./EasyDotnet.IDE.Tests/EasyDotnet.IDE.Tests.csproj
          dotnet run --no-build --project ./EasyDotnet.MsBuild.Tests/EasyDotnet.MsBuild.Tests.csproj
