name: 📦Publish .NET Tool to NuGet

on:
  push:
    branches:
      - main

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'

      - name: Restore dependencies
        run: dotnet restore

      - name: Build Release + Inject Roslyn
        uses: ./.github/actions/build-release-with-roslyn

      - name: Pack
        run: dotnet pack ./EasyDotnet.IDE

      - name: Push to NuGet (ignore conflict errors)
        run: |
          dotnet nuget push EasyDotnet.IDE/bin/Release/*.nupkg \
            --api-key ${{ secrets.NUGET_API_KEY }} \
            --source https://api.nuget.org/v3/index.json \
            --skip-duplicate
